### ISSUE TITLE
index.d.ts

### ISSUE THREAD

**Issue by orefalo** [tlivings/graphql-component#15]
Adding this file at the root under index.d.ts will make typescript users happy ;-)

Tks

export declare class GraphQLComponent {
    _schema: any;
    _types: any[];
    _resolvers: any;
    _imports: any[];
    _directives: any;
    _context: any;
    _importedTypes: any[];
    _importedResolvers: any;
    _useMocks: boolean;
    _importedMocks: any;
    _mocks: any;
    _preserveTypeResolvers: boolean;
    _fragments: any;
    _mergedTypes: any;
    _mergedResolvers: any;
    constructor({ types, resolvers, imports, mocks, directives, context, useMocks, preserveTypeResolvers }?: {
        types?: any[];
        resolvers?: {};
        imports?: any[];
        mocks?: any;
        directives?: any;
        context?: any;
        useMocks?: boolean;
        preserveTypeResolvers?: boolean;
    });
    static isComponent(check: any): any;
    execute(input: any, { root, context, variables }?: {
        root?: any;
        context?: {};
        variables?: {};
    }): Promise<any>;
    readonly schema: any;
    readonly context: {
        (arg: any): Promise<any>;
        use(name: any, fn: any): void;
    };
    readonly types: any[];
    readonly importedTypes: any[];
    readonly resolvers: any;
    readonly importedResolvers: any;
    readonly imports: any[];
    readonly mocks: any;
}

**Comment by tlivings** [comment]
Thanks! Will do.

**Comment by tlivings** [comment]
Also feel free to PR :)

**Comment by tlivings** [comment]
Added
