### ISSUE TITLE
what is exposed should be declarative, not exclusionary.

### ISSUE THREAD

**Issue by patdmc** [tlivings/graphql-component#3]
It would be cleaner if the component explicitly declared which queries and mutations to include, rather than what to exclude. that is a cleaner mental model for the component since you are stating what you want rather than filtering out what you dont. an empty config should just include all

**Comment by tlivings** [comment]
The main use case I see for this feature is where one component includes another but excludes its api for public consumption. How is inclusion clearer?

**Comment by tlivings** [comment]
Semantically I am seeing it as “import X, exclude X.a” rather than “import X, include X.a” which seems to be repetitive.
